### ISSUE TITLE
Is it possible to add price limit for products?

### ISSUE THREAD

**Issue by pr110** [tnware/product-checker#4]
Sometimes a product link will give back a marketplace links (walmart specifically). Certain sites don't have the offer pages like Amazon. Is there a work around?

Also, Is it possible to change the link that it spits out. Obviously the links imputed has to normal, but is there a way to have it spit out affiliate links, different from the imputed one?

**Comment by tnware** [comment]
i am not going to implement the ability to send a referral link instead of a link to the product being tracked.

to address your immediate concern with walmart links, the latest update includes price (and now title) and sends that along in the notification, so you can decide whether or not you want to click the page or not.

this is a stock tracker, maybe in a future release i will add logic to consider the price as well as the stock status.

![image](https://user-images.githubusercontent.com/537897/80893651-f5cd9f80-8c99-11ea-9f35-b995c029bdec.png)
