### ISSUE TITLE
Target false positives

### ISSUE THREAD

**Issue by BrendanBTO** [tnware/product-checker#6]
Getting in stock alerts for Target. When checking there’s nothing in stock whether online or stores nearby. Perhaps it’s grabbing something from comments section?

**Comment by tnware** [comment]
As long as the page says "Temporarily out of stock", the script marks it as out of stock. If this status goes away for any reason then you will get the in stock notification.

If the page says "Sold Out" or something to that effect instead of "Temporarily out of stock" then it will trigger a false positive.

![image](https://user-images.githubusercontent.com/537897/81754432-cc6ff900-947b-11ea-83a1-10a133c069f7.png)

**Comment by BrendanBTO** [comment]
OK so no way to adjust the code for Target to avoid the false positives?

**Comment by tnware** [comment]
I would need for you to give me some information like what does it say instead of “temporarily out of stock”?

**Comment by 0xv1n** [comment]
Why not just do a `if "out of stock" in page.text.lower():` rather than only checking against "Temporarily out of stock"? You cover both the "Out of stock" and that one as well.

**Comment by 0xv1n** [comment]
Or better yet, check for the shipping/pickup buttons rather than text on the page.

**Comment by tnware** [comment]
I've improved the target page parsing. The script searches for a more generic status message now in a JSON payload of the page source:

"availability_status": "OUT_OF_STOCK" 

or

"availability_status": "IN_STOCK"

in case there are other status that I have not found yet, I included a method to debug, so the script will say it doesn't know how to handle "new status message" whatever it is, if it's not "out_of_stock" or "in_stock", but those are the only two i could find so this looks good to go.
